#!/bin/sh
set -eux

nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
nix-channel --update

nix build -f release.nix commit --argstr commit $GITHUB_SHA
nix-shell -p rsync --run 'mkdir tmp; rsync result/* tmp/; rm result; mv tmp result'
