name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # ---------------------------------------------------------------------
      # Setup

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      # ---------------------------------------------------------------------
      # Build

      - run: ./node_modules/.bin/tsc

      - run: cat package.json | jq 'del(.devDependencies)' > dist/package.json

      - run: rm dist/*.test.*

      # ---------------------------------------------------------------------
      # Publish

      - run: pnpm publish --registry https://registry.npmjs.org --access public --no-git-checks
        working-directory: dist/
