name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # ---------------------------------------------------------------------
      # Setup

      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      # ---------------------------------------------------------------------
      # Build

      - run: ./node_modules/.bin/tsc

      - run: cat package.json | jq 'del(.devDependencies)' > dist/package.json

      - run: rm dist/*.test.*

      # ---------------------------------------------------------------------
      # Publish

      - run: pnpm publish --registry https://registry.npmjs.org --access public --no-git-checks
        working-directory: dist/
