name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      - run: |
          if ./node_modules/.bin/changeset status --output=release.json 2>/dev/null; then
            echo "VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          title: "Release ${{ env.VERSION }}"
          commit: "Release ${{ env.VERSION }}"
