name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      - run: |
          if ./node_modules/.bin/changeset status --output=release.json 2>/dev/null; then
            echo "VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          title: "Release ${{ env.VERSION }}"
          commit: "Release ${{ env.VERSION }}"
